### ISSUE TITLE
AR Issues and Observations

### ISSUE THREAD

**Issue by ct-klein** [pyure/infitech-prototype#191]
Version: 0.23 build

Issues:
AR machine structure (vulpes library) recipe does not work (4 iron plates)
AR Advanced machine structure recipe does not work (4 titanium plates)
AR Rocket Fuel needs a chemical reactor recipe for GT.  AR recipe is 10mb Oxygen/10mb Hydrogen = 20mb Rocket Fuel

Observations:
AR Solar generator produces 1 RF/t, the energy pipe from AR has been deprecated, so fluxducts may be needed.

AR Electric Arc furnace, do we want to allow this in addition to the EBF? 
5 recipes for the electric arc furnace;
sand->1 silicon ingot
iron/coal->1 steel ingot
7aluminum/3titanium->3 titanium aluminide ingot
titanium/iridium->2 titanium iridium alloy ingot
rutile ore->titanium ingot (probably not a problem since the ore doesn't exist)

AR machines seem to have an issue with materials.  Rolling machine, for example, 1 iron ingot=1 iron plate. 64 iron ingots=1 iron plate.
Same issue with lathe, electric arc furnace, cutting machines.
Crystallizer has same issues with silicon ingot/nugget
Not really an IT3 issue more than a AR mod issue.

On the moon, dilithium ore is located but very rarely. 2-4 ores per cluster and well scattered.  Other GT ores seem to spawn normally along with the 'nuggets' on the surface denoting their presence. 

I'd just leave this ticket open for a bit, I'll add more to it as I progress thru the pack.

**Comment by ct-klein** [comment]
Data, fluid and energy cables are marked as deprecated in the AR pack.  I'm not sure where that came from but I 'think' the DATA cables might be needed to get information from Observatory/Astrobody data processor as well as anything else in AR with a data port.

Fluid/energy can probably get by without, energy cables are used to daisy-chain solar generators together but I haven't seen a use and fluid can use fluiducts/xnet/etc.

**Comment by ct-klein** [comment]
There is an update required to LibVulpes to fix an issue of item loss in AR.  1.12.2-0.2-8.35 or greater

**Comment by RedBlockFilms** [comment]
To add on to the cable part, there's a new block called the wireless transceiver for data. Here's the page for it, it's just a wireless data item. http://arwiki.dmodoomsirius.me/AdvancedRocketry/blocks/WirelessTransciever.php

**Comment by ct-klein** [comment]
the wireless transceivers work like a charm, been using them for a bit just forgot to make mention of it.

**Comment by pyure** [comment]
@ct-klein I'm gonna spin up some tasks.  See below:

* Fix Machine Structure recipe (currently 4 iron plates)
* Fix Advanced Machine Structure (4 titanium plates)
* Add (DESIGN) Rocket Fuel recipe for Chemical Reactor (Currently 10 Oxygen + 10 Hydrogen => 20 Rocket Fuel)
* Un-deprecate Fluxducts (With CEU mod and no other perfect-transform-power solutions on the horizon, we don't need them)
* Disable the AR Arc Furnace and attribute its recipes as follows:
  * 7 Aluminium + 3 Titanium -> (BLAST FURNACE) -> 2 Titanium Aluminide Ingot 
  * Titanium + Iridium -> (BLAST FURNACE) ->  2 Titanium Iridium Alloy Ingot 
* No changes at this time for AR machines, specifically because we'll need "clever" designs.  I don't want to outright disable the machines cuz they're kinda sexy.
* No changes required for the deprecating wiring
* No changes required for the oregen at this time (I'm a bit surprised the dilithium spawns at all tbh)

**Comment by ct-klein** [comment]
As part of a conversation with Pyure, the default planetary gas mining operation with nothing else defined in the configuration returns Oxygen, Hydrogen and Nitrogen.

**Comment by ct-klein** [comment]
There is a fix for being unable to launch unmanned vehicles on gas giants.  Current build for AR is 104, it is corrected in anything build 111 or newer.  Verified working in 114.
