### ISSUE TITLE
Food config

### ISSUE THREAD

**Issue by dymorius** [pyure/infitech-prototype#293]
Some things usually inedible are edible, like Pam's Harvestcraft's cotton plant and vanilla wheat

**Comment by pyure** [comment]
Weird.  Its not specifically Pams for sure (tested).
Anyone have a guess which mod might be causing this?

**Comment by garlicinyoureye** [comment]
Could this be from appleskin having values for those items as edible?

**Comment by pyure** [comment]
I thought I ruled out Pam's, but tonight I noticed the issue happening with Cotton with ONLY Pam's installed.

It turns out anything from Pam's that is a Crop is edible.  Wheat specifically has a config option to make it inedible, but I'm not really inclined to disable it since its the most foody of these non-foods.  I'm closing this since there's really not much we can do other than install a heavy mod like Hunger Overhaul or setting all crops to zero food.

**Comment by pyure** [comment]
fwiw, if ppl really decide they care, we can change the food value of specific items to zero using https://www.curseforge.com/minecraft/mc-mods/hungertweaker

<harvestcraft:cottonitem>.foodValues.hunger = 0;
<harvestcraft:cottonitem>.foodValues.saturationModifier = 0;
