### ISSUE TITLE
Void plates issue

### ISSUE THREAD

**Issue by Waisse** [pyure/infitech-prototype#319]
https://cdn.discordapp.com/attachments/508670711670243346/540495611036696576/unknown.png

Seems to be the only recipe to make it, it might be a bug.

**Comment by Waisse** [comment]
Crap I mean void metal plate, I can't edit sorry.

**Comment by Agrax** [comment]
Here to help

**Comment by Agrax** [comment]
But probably pyure's question stands: is there any use for voidmetal plates?

**Comment by XXxinsanityxX** [comment]
I was looking into the different scripts one day and i found a bug in the thaumcraft script, in line 25 its adding a recipe for thaumium plates from void ingots instead of void plates.

_24 recipes.remove(<thaumcraft:plate:3>); **Here the void plate recipe is removed**
25 recipes.addShaped(<thaumcraft:plate:2>, [ **Here is the error its adding a recipe to the wrong item**
26 	[<ore:craftingToolHardHammer>],
27	[<ore:ingotVoid>],
28 [<ore:ingotVoid>]]);_

**Comment by Waisse** [comment]
So yeah, there is 2 issues concerning void metal plates :

- Their only recipe is with the Rolling machine from AR
- A recipe using 2 void metal ingot and a GT hammer give a thaumium plate instead of a void metal plate

**Comment by Agrax** [comment]
Fixed via #322

**Comment by pyure** [comment]
Released in infitech-prototype-0.36.zip
