### ISSUE TITLE
Finish Agricraft Plant product mechanisms

### ISSUE THREAD

**Issue by pyure** [pyure/infitech-prototype#377]
Since I misplaced stuff somehow.

**Comment by TLaviron** [comment]
Is it going to be possible to pull water from the agricraft tanks into other stuff (e.g. Gregtech machines)?
Is this already possible and I haven't figured out how?

I have tried placing gregtech pipes next to an agricraft tank, it visually connects, but does not fill with water. I tried adding a pump on the side of the pipe in import mode, but that didn't help either.

I'd love to have a pipe network to get water into my machines, instead of carrying buckets around all the time...

**Comment by pyure** [comment]
Yep the whole point of the agricraft tanks in fact is to handle your early-game water requirements.

Any block/pipe which can "pull" water will work. Off the top of my head: 

- Buildcraft wooden fluid pipes with a redstone engine.  
- Ceramics with a faucet (not recommend)
- fluiducts with a servo
- liquid hopper from pneumaticraft (will get nerfed recipe at some point)

(FWIW this ticket is regarding the plants/mutations work that I apparently failed to complete)

**Comment by TLaviron** [comment]
Thanks for the tip, I will try some of those, and sorry for the slightly off-topic comment.

**Comment by pyure** [comment]
Fixed in infitech-prototype-0.42b
