### ISSUE TITLE
Loam Blocks from Foresty destroy wood pile

### ISSUE THREAD

**Issue by garlicinyoureye** [pyure/infitech-prototype#498]
Wood pile blocks are being destroyed while using Loam blocks on all sides of the structure. Do the corners need to be filled in as well?  Top, bottom, side and top were loam and resulted in all blocks being destroyed.

**Comment by Xavion3** [comment]
This issue is normally related to have empty air blocks within the charcoal pile, not the walls. Actually walls shouldn't affect at all whether the wood pile vanishes, even invalid blocks should just cause no charcoal to be dropped by the resulting ash. So yeah, how certain are you the entire internal space was filled with no gaps? Get the basic questions out of the way first.

**Comment by garlicinyoureye** [comment]
100% certain that the entire air space was full with wood pile blocks from forestry.  I scaled back my set up to a 3x3 internal areal completely surrounded by loam, including the corners.  Lite the wood pile and covered back with loam.  I could hear the pile burning, returned 10 or so mins later and there was nothing inside.

**Comment by garlicinyoureye** [comment]
I just tested this in creative and it worked as intended from Forestry.  I will try to recreate the issue.  Frustrating.

**Comment by pyure** [comment]
fyi corners shouldn't be necessary, just every block touching a wood pile. Hopefully you just missed a spot..
