### ISSUE TITLE
[suggestion] Scannable

### ISSUE THREAD

**Issue by Agrax** [pyure/infitech-prototype#500]
https://minecraft.curseforge.com/projects/scannable

Look this mod up. Make it HV or smth. Dunno. It’s just so much easier to use than prospectors which are killing me at the point in game im at

**Comment by pyure** [comment]
Will keep an eye on this.  HV is a good idea if we go with it.

Prospectors is getting really good feedback so far, but the players providing that feedback aren't doing HV-level ore-searches yet.

**Comment by Agrax** [comment]
Yeah. Find manganese (no nugget) with just prospectors and i’ll buy you a beer. Im not saying that you should *remove* prospectors. Just add the mod from the title

**Comment by pyure** [comment]
Agrax, I looked into this today.  I'm closing it because its too much work for too little gain.

* Ore-searching has a pretty limited range.  I can theoretically only configure it to look for ores 32 blocks away (with a boosting upgrade I think its 48 blocks, not sure)
* I don't want to try to define colors for every possible GT ore
* I don't want all ores to share a color
* Players are finding manganese (or manganese-byproduct ores) with just prospectors and meteorite compass just fine
