### ISSUE TITLE
Invar inconsistencies

### ISSUE THREAD

**Issue by josiah-roberts** [pyure/infitech-prototype#512]
I'm not sure if this is a config issue, or a Foundary issue.

![image](https://user-images.githubusercontent.com/37082009/57183315-bb9ba900-6e5f-11e9-8a2a-492e67fdc850.png)

**Comment by pyure** [comment]
Hey josiah-roberts.  This is intentional: a couple months ago we reduce the number of metals/alloys you could work with in Foundry.  Invar was pretty much the cutoff.

The idea is that we wanted to keep Foundry "very early game".  I may look at ensuring you cannot even melt the stuff at some point in the future just to keep things a bit more clear.

For your reference, these can all be made into plates.  The lists for Gears, Rods, and Tools are mostly similar, and none allow Invar.
 ```
 "Cobalt" : 1650,
  "Gold" : 800,
  "Iron" : 1400,
  "Tin" : 800,
  "TinAlloy" : 1100,
  "Copper" : 800,
  "Lead" : 1300,
  "Nickel" : 1200,
  "Silver" : 700,
  "Brass" : 1200,
  "Bronze" : 1100,
  "WroughtIron" : 1550,
  "CompressedWroughtIron" : 1690,
  "RedAlloy" : 1200
```

**Comment by josiah-roberts** [comment]
Thanks for the clarification, @pyure. It would be best to disable it entirely I think - I poured a bunch of invar into a metal caster and couldn't get it out, wasting it, and then realized the ingot cast works. I totally get disabling it though - 2x the durability and decent speed bump over iron just for adding a bit of nickel is pretty powerful, and historically speaking it didn't show up until around 1900 so it's plausible that it's beyond the foundry from that standpoint as well.
