### ISSUE TITLE
Few things from GT5

### ISSUE THREAD

**Issue by Aprax88** [pyure/infitech-prototype#591]
hello dear mod creator!

I would like to know. will disassembler be added? as the game progresses, old mechanisms accumulate which cannot be further processed into resources or melted in an arc furnace. 
I would also like to know. Will a mode of lowering steam production be added to multi-block boilers by reducing efficiency with the help of a microcircuit as it was in GT5?

**Comment by pyure** [comment]
Hiya Aprax:
These are technically questions for GT-CE itself rather than a modpack, but I can possibly help you:
1) As far as I know there are no plans to add a dissassembler machine.  It didn't work very well in GT5 (since it depended on nbt for the most part, which didn't always exist).  Infitech3 may at some point add recycling recipes however to arc furnaces etc (but not at 100% recovery obviously)
2) GT-CE has already added a mechanism to lower steam production in the boilers; its not released yet.
