### ISSUE TITLE
Inductive Logistics fluid duplication issue

### ISSUE THREAD

**Issue by pyure** [pyure/infitech-prototype#96]
Reported by several alpha testers.

https://github.com/CD4017BE/InductiveLogistics/issues/32

**Comment by pyure** [comment]
This is possibly resolved on the dev's end.  Waiting on a subsequent version release.

**Comment by Black0305** [comment]
Duplication seems to be fixed in new version.
However you can still insert more water than you should be able to, resulting in a visual bug.
![il1](https://user-images.githubusercontent.com/42079463/44990289-dcd68d80-af90-11e8-89e0-b94e17bbc8a7.JPG)
![il2](https://user-images.githubusercontent.com/42079463/44990295-dea05100-af90-11e8-9d68-c9da35680ac0.JPG)

**Comment by Black0305** [comment]
1. Place IL Tank, fill it with water and attach two Fluiducts with a servo to extract water (Fluiduct an tank need to be full)
2. Break  second Fluiduct

**Comment by Black0305** [comment]
Some other IL Bugs that I encountered.
1. Shift klicking a Bucket in an IL tank wont update its texture so the bucket looks full although the content is transfered in the tank.
2. Placing a bucket inside the tank, drop another bucket onto the first one --> first bucket dissappears, doesnt matter if the bucket is full or empty. You can even destroy full stacks of empty buckets with this.

Can anyone confirm this?

**Comment by Agrax** [comment]
Damn, IL is so buggy in that case

**Comment by Agrax** [comment]
Can be closed

**Comment by pyure** [comment]
Fixed via removal of mod.
